extends SceneTree
## Every authored route uses public actions. No item grants or progress injection.
const GameState = preload("res://scripts/game_state.gd")
var assertions := 0
var failures: Array[String] = []
var route_label := ""

func _init() -> void:
	_run.call_deferred()

func _check(ok: bool, message: String) -> void:
	assertions += 1
	if not ok:
		failures.append(route_label + ": " + message)
		printerr("FAIL: " + failures.back())

func _go(game, destination: String) -> void:
	# The map itself may choose a path; each transition still uses the model gate.
	var queue: Array = [[game.room]]
	var visited: Array = []
	while not queue.is_empty():
		var path: Array = queue.pop_front()
		var node: String = path.back()
		if node == destination:
			for step in path.slice(1): game.travel(step)
			_check(game.room == destination, "Travel reached " + destination)
			return
		if visited.has(node): continue
		visited.append(node)
		for exit in game.rooms[node].exits:
			if game.is_unlocked(exit.id): queue.append(path + [exit.id])
	_check(false, "No open path to " + destination)

func _choose(game, id: String) -> String:
	var ids: Array = game.dialogue_options().map(func(option): return option.id)
	_check(ids.has(id), "Choice visible: " + id)
	return game.choose_dialogue(id)

func _snapshot(game) -> String:
	return JSON.stringify({"room": game.room, "inventory": game.inventory, "flags": game.flags, "cash": game.cash, "score": game.score, "turns": game.turns, "journal": game.journal, "completed": game.completed})

func _route(mask: int, tone: String) -> void:
	route_label = "route %d / %s" % [mask, tone]
	var game = GameState.new()
	game.command("take newspaper")
	game.command("read newspaper")
	var social_access := (mask & 1) != 0
	var rehearsal := (mask & 2) != 0
	var social_hotel := (mask & 4) != 0
	_go(game, "bar")
	if social_access:
		game.command("talk lefty")
		_choose(game, "promotion_brief")
		var before: int = game.cash
		_choose(game, "promotion_larry")
		_choose(game, "promotion_bouncer")
		_choose(game, "promotion_regular")
		_check(not game.is_unlocked("backroom") and game.cash == before, "Unsupported guess opens nothing and spends nothing")
		game.command("look promotion")
		game.command("talk regular")
		_choose(game, "regular_ticket")
		game.command("talk lefty")
		var lefty_referral: String = _choose(game, "promotion_regular")
		_check(lefty_referral.contains("Didi") and lefty_referral.contains("Studio 69") and lefty_referral.contains("casino's clean ashtray"), "Social payoff supplies the next chapter lead without the HUD objective")
		_check("\n".join(game.journal).contains(GameState.DIDI_REHEARSAL_CLUE), "Heard social referral remains in the notebook")
		_check(game.is_unlocked("backroom"), "Matching observed evidence earns backstage access")
		_check(not game.flags.get("tv_distracted", false) and not game.flags.get("password_spoken", false), "Social route is independent of caper flags")
	else:
		game.command("buy whiskey")
		game.command("give whiskey to regular")
		game.command("use remote on tv")
		var bouncer: String = game.command("talk bouncer")
		_check(bouncer.contains("Thanks for the bowling") and not bouncer.contains("finds the remote"), "TV-before-password does not repeat stale remote request")
		_check(not game.objective().contains("put bowling"), "Objective recognizes completed television step")
		_go(game, "bathroom")
		game.command("read graffiti")
		_go(game, "bar")
		game.command("talk bouncer")
		_check(game.is_unlocked("backroom"), "Caper independently opens backstage")
	_go(game, "backroom")
	var backstage: String = game.command("look")
	var poster: String = game.command("look poster")
	_check(backstage.contains("Studio 69") and backstage.contains("clean ashtray"), "Backstage arrival provides an authored next-chapter lead on either access route")
	_check(poster.contains("Didi") and poster.contains("pass") and poster.contains("casino"), "Examining the poster supplies the pass location and person to meet")
	if not rehearsal:
		_go(game, "street")
		game.command("buy flowers")
		_go(game, "bathroom")
		game.command("take ring")
		_go(game, "backroom")
		game.command("take candy")
	_go(game, "casino")
	game.command("take pass")
	_go(game, "disco")
	game.command("talk didi")
	if rehearsal:
		_choose(game, "rehearsal_start")
		_choose(game, "rehearsal_wrong")
		_check(not game.flags.get("phone_known", false), "Funny wrong cue permits retry but doesn't complete rehearsal")
		_choose(game, "rehearsal_correct")
		_check(game.flags.get("phone_known", false) and not game.flags.get("gift_ring", false), "Rehearsal needs no gift route")
		_choose(game, "dance_copy")
	else:
		_choose(game, "dance_confident")
		_check(not game.objective().contains("dance still needed"), "Completed dance drops out of remaining subgoals")
		game.command("give flowers to didi")
		game.command("give ring to didi")
		game.command("give candy to didi")
		_check(game.flags.get("phone_known", false), "Original props and dance still earn the introduction")
	game.command("talk didi")
	_choose(game, "show_start")
	if tone == "ending_friends":
		_choose(game, "skip_show")
		_check(game.flags.get("show_completed", false) and game.flags.get("show_skipped", false), "Skip show retains full chapter access")
	else:
		var first: String = _choose(game, "show_next")
		_check(first.contains("AUDIT") if rehearsal else first.contains("costume ring"), "Show recalls chosen rehearsal route")
		var second: String = _choose(game, "show_next")
		_check(second.contains("golden-pin") if social_access else second.contains("bowling broadcast"), "Show recalls chosen backstage route")
		_choose(game, "show_next")
		_check(game.flags.get("show_completed", false), "Show reaches curtain call")
	_check(not game.objective().contains("watch her show") and game.objective().contains("curtain-call"), "Objective acknowledges a completed performance")
	var stable := _snapshot(game)
	game.choose_dialogue("show_next")
	_check(_snapshot(game) == stable, "Stale completed-show choice has no side effects")
	game.command("use phone")
	_check(game.flags.get("phone_called", false), "Stage manager reached")
	if social_hotel:
		_choose(game, "manager_setup")
		_choose(game, "manager_intro")
		_go(game, "hotel")
		game.command("talk receptionist")
		_choose(game, "hotel_introduction")
		_check(game.flags.get("penthouse_access", false) and not game.flags.get("spent_coffee", false), "Social hotel route needs neither coffee nor window")
		_check(not game.command("look receptionist").contains("espresso you brought"), "Social route does not invent a coffee delivery")
		_check(not game.command("look").contains("sips your espresso"), "Hotel scenery reflects actual route")
	else:
		_go(game, "shop")
		game.command("buy wine")
		_go(game, "alley")
		game.command("give wine to busker")
		game.command("take mallet")
		_go(game, "disco")
		game.command("use knife on spare rope")
		_go(game, "backroom")
		game.command("use rope on railing")
		_go(game, "balcony")
		game.command("use mallet on window")
		game.command("take voucher")
		_go(game, "shop")
		game.command("use voucher on espresso machine")
		_go(game, "hotel")
		game.command("give coffee to receptionist")
		_check(game.flags.get("penthouse_access", false) and game.flags.get("coffee_delivered", false), "Original coffee caper opens hotel")
	_go(game, "rooftop")
	game.command("talk eve")
	_choose(game, "eve_dinner")
	_choose(game, "eve_boast" if tone == "ending_afterparty" else "eve_story")
	var garden_topic: String = _choose(game, "eve_gardens")
	_check(garden_topic.contains("Service Alley") and garden_topic.contains("separate the seeds"), "Eve explains both the missed seed source and extraction action")
	_choose(game, "eve_followup")
	_choose(game, "cultivar_midlife")
	var exhausted: String = game.command("talk eve")
	_check(not exhausted.contains("Choose a topic") and exhausted.contains("Service Alley"), "Exhausted Eve topics give a concrete fruit lead instead of an empty choice prompt")
	_check(not game.completed, "Conversation before fruit delivery never auto-finishes")
	_go(game, "alley")
	game.command("take apple core")
	game.command("use apple core")
	var seeds_before: Array = game.inventory.duplicate()
	game.command("use seeds on busker")
	_check(game.inventory == seeds_before, "Wrong seed target preserves unique seeds")
	_go(game, "garden")
	game.command("take stool")
	game.command("plant seeds")
	var planted_inventory: Array = game.inventory.duplicate()
	var water_lead: String = game.command("use planter")
	_check(water_lead.contains("already planted") and water_lead.contains("water pitcher") and water_lead.contains("penthouse cabinet"), "Using planted bed without a pitcher asks only for the remaining water step")
	_check(game.inventory == planted_inventory and game.flags.get("seeds_planted", false), "Reading the remaining planter step preserves seeds and inventory")
	_go(game, "penthouse")
	game.command("use stool on cabinet")
	game.command("take pitcher")
	game.command("fill pitcher")
	_go(game, "garden")
	game.command("water planter")
	game.command("take apple")
	_check(game.inventory.has("apple"), "Fruit remains obtainable on every route")
	_check(game.item_status("pitcher") == "souvenir", "Spent-purpose pitcher marked souvenir without being discarded")
	var apple_before: Array = game.inventory.duplicate()
	game.command("use apple on planter")
	_check(game.inventory == apple_before, "Wrong apple target preserves final gift")
	_go(game, "rooftop")
	game.command("give apple to eve")
	game.command("talk eve")
	_check(not game.completed, "Explicit-choice conversation does not auto-select flirt ending")
	var output: String = _choose(game, tone)
	_check(game.completed and output.contains("THE END"), "Chosen ending completes evening")
	_check(game.flags.get(tone, false), "Chosen tone is persisted explicitly")
	_check(game.score <= game.max_score, "Exploration score is capped")
	_check(game.epilogue().contains("golden pin") if social_access else game.epilogue().contains("channel six"), "Epilogue remembers backstage route")
	_check(game.epilogue().contains("Written Off") if rehearsal else game.epilogue().contains("ring, flowers"), "Epilogue remembers Didi route")
	stable = _snapshot(game)
	game.choose_dialogue(tone)
	game.choose_dialogue("grant_everything")
	_check(_snapshot(game) == stable, "Unknown or repeated ending cannot mutate score/items/turns")
	var path := "user://upgrade_route_test_%d_%s.json" % [mask, tone]
	_check(game.save_game(path).contains("saved"), "Ending saves")
	var restored = GameState.new()
	_check(restored.load_game(path).contains("restored"), "Ending reloads")
	_check(_snapshot(restored) == stable and restored.ending_text() == game.ending_text() and restored.epilogue() == game.epilogue(), "Save reload preserves exact ending and callbacks")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	if mask == 7: _check(game.score < 100, "A complete evening need not require every optional milestone")

func _run() -> void:
	for mask in range(8):
		for tone in ["ending_flirt", "ending_friends", "ending_afterparty"]:
			_route(mask, tone)
	route_label = "clue and compatibility invariants"
	var game = GameState.new()
	var original := _snapshot(game)
	game.choose_dialogue("ending_flirt")
	_check(_snapshot(game) == original, "Unavailable ending has no mutation")
	_check(not "\n".join(game.journal).contains("ticket 37"), "Fresh game notebook contains no undiscovered prize solution")
	_check(not "\n".join(game.journal).contains(GameState.DIDI_REHEARSAL_CLUE), "Fresh notebook does not invent an unheard Didi referral")
	_check(not "\n".join(game.journal).contains("Service Alley bin lid"), "Unobserved seed source is not injected into fresh notebook")
	_check(game.hint_level(0) != game.hint_level(1) and game.hint_level(1) != game.hint_level(2), "All three hint levels are distinct")
	_check(not game.hint_level(0).contains("37") and not game.hint_level(0).contains("BELLYBUTTON"), "First hint avoids exact opening solution")
	_go(game, "bar")
	game.command("look promotion")
	game.command("look regular")
	var notes_before: int = game.journal.size()
	game.command("look promotion")
	game.command("look regular")
	_check(game.journal.size() == notes_before, "Observed puzzle clues are deduplicated")
	_go(game, "bathroom")
	_check("\n".join(game.journal).contains("JEWELRY dish"), "Visited visible item source becomes a durable notebook lead")
	var observer = GameState.new()
	_go(observer, "hotel")
	_go(observer, "garden")
	var planter_clue: String = observer.command("look planter")
	_check(planter_clue.contains("SERVICE ALLEY BIN LID") and planter_clue.contains("apple core"), "Looking at the planter reveals a seed-source clue without an alley visit")
	_check("\n".join(observer.journal).contains(GameState.SEED_SOURCE_CLUE), "Observed planter clue persists in notebook")
	var clue_count: int = observer.journal.size()
	observer.command("look planter")
	_check(observer.journal.size() == clue_count, "Repeated source clue does not duplicate notebook entry")
	_go(observer, "street")
	observer.command("take newspaper")
	var article: String = observer.command("read newspaper")
	_check(article.contains("Service Alley") and article.contains("separate the seeds"), "Newspaper explains core source and extraction directly")
	# Older version-one files have no new route/tone flags. They remain loadable.
	var old_save := "user://upgrade_legacy_test.json"
	var file := FileAccess.open(old_save, FileAccess.WRITE)
	file.store_string(JSON.stringify({"version": 1, "room": "rooftop", "inventory": [], "flags": {"penthouse_access": true, "apple_given": true, "eve_met": true, "eve_story_shared": true, "eve_heard": true, "award_ending": true}, "cash": 48, "score": 100, "turns": 85, "completed": true, "journal": ["An old evening."]}))
	file.close()
	_check(game.load_game(old_save).contains("restored") and game.completed, "Legacy version-one completed save remains valid")
	_check(game.ending_title() == "A LITTLE CONNECTION" and not game.ending_text().is_empty(), "Legacy ending gets compatible default tone")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(old_save))
	print("Upgrade route tests: %d assertions, %d failures; 8 route combinations × 3 ending tones." % [assertions, failures.size()])
	quit(0 if failures.is_empty() else 1)
