extends SceneTree
## Player-visible clues must reflect real progress through the adventure.

const GameState = preload("res://scripts/game_state.gd")
var game = GameState.new()
var assertions := 0
var failures: Array[String] = []


func _init() -> void:
	_run.call_deferred()


func _check(condition: bool, message: String) -> void:
	assertions += 1
	if not condition:
		failures.append(message)
		printerr("FAIL: " + message)


func _commands(commands: Array) -> void:
	for command in commands:
		game.command(command)


func _run() -> void:
	_commands(["take newspaper", "read newspaper", "buy flowers", "go bar"])
	var notes_before: int = game.journal.size()
	var score_before: int = game.score
	_commands(["talk regular", "talk regular", "look regular"])
	_check(game.journal.size() == notes_before + 1, "Regular's learned trade is recorded once across LOOK/TALK")
	_check(game.score == score_before, "Ordinary conversation notes do not award points")
	_commands(["buy whiskey", "give whiskey to regular"])
	_check(game.command("talk regular").contains("remote's yours"), "Regular remembers giving away the remote")
	_check(game.command("look regular").contains("You have his remote"), "Regular LOOK reflects completed trade")
	_check(game.command("look").contains("raises the whiskey"), "Bar room description reflects the trade")
	_commands(["go bathroom", "read graffiti", "take ring"])
	_check(game.command("look basin").contains("empty"), "Jewelry dish is empty after ring pickup")
	_check(game.command("look").contains("empty"), "Restroom prose no longer promises another ring")
	_commands(["go bar", "BELLYBUTTON"])
	var television: String = game.command("use remote on tv")
	_check(television.contains("has your password") and not television.contains("Provide the password"), "TV success acknowledges an already accepted password")
	_check(game.command("look").contains("bowling"), "Bar description no longer describes static")
	var arrival: String = game.travel("backroom")
	_check(arrival == game.command("look"), "Travel and LOOK use the same current room description")
	game.command("take candy")
	_check(game.command("look").contains("chocolates are gone"), "Backstage prose reflects collected candy")
	_commands(["go bar", "go street", "go casino", "take pass"])
	_check(game.command("look ashtray").contains("empty"), "Ashtray no longer instructs taking the collected pass")
	_check(game.command("look").contains("empty"), "Casino prose reflects the collected pass")
	_commands(["go street", "go disco", "talk didi", "dance", "give ring to didi"])
	var didi: String = game.command("talk didi")
	_check(didi.contains("flowers") and didi.contains("chocolates") and not didi.contains("costume ring"), "Didi requests only props still missing")
	_commands(["give flowers to didi", "give candy to didi", "call 555-0987"])
	score_before = game.score
	var inventory_before: Array = game.inventory.duplicate()
	didi = game.command("talk didi")
	_check(didi.contains("pass on") and didi.contains("tell him myself"), "Didi acknowledges the manager's invitation without another required errand")
	notes_before = game.journal.size()
	didi = game.command("talk didi")
	_check(didi.contains("show's ready") and not didi.contains("555-0987"), "Didi's completed subplot gets a closing callback")
	_check(game.journal.size() == notes_before, "Repeated Didi follow-up does not duplicate notes")
	_check(game.score == score_before and game.inventory == inventory_before, "Optional Didi follow-up changes no score or inventory")
	_check(game.command("look phone").contains("has his message"), "Phone LOOK acknowledges delivered message")
	_commands(["go street", "go shop", "talk clerk"])
	notes_before = game.journal.size()
	_commands(["go street", "go hotel", "talk receptionist", "talk receptionist"])
	_check(game.journal.size() == notes_before, "Clerk and receptionist record the same coffee clue only once")
	_commands(["go street", "go alley"])
	notes_before = game.journal.size()
	_commands(["talk busker", "look busker", "talk busker"])
	_check(game.journal.size() == notes_before + 1, "Busker's learned trade survives in the notebook without duplicates")
	_commands(["go street", "go shop", "buy wine", "go street", "go alley", "give wine to busker"])
	_check(game.command("talk busker").contains("knife's yours"), "Busker remembers the completed wine trade")
	_check(game.command("look busker").contains("gave you"), "Busker LOOK reflects the completed trade")
	_commands(["take mallet", "take apple core", "use apple core"])
	_check(game.command("look").contains("bin lid is clear") and game.command("look").contains("empty mallet hook"), "Alley prose reflects both collected objects")
	_commands(["go street", "go disco", "use knife on spare rope"])
	_check(game.command("look rigging").contains("collected"), "Rigging no longer offers a second spare coil")
	_check(game.command("call 555-0987").contains("You've got the rope"), "Repeated phone call acknowledges rope collection")
	_commands(["go street", "go bar", "go backroom"])
	_check(game.command("look poster").contains("thanks to you"), "Cabaret poster provides a callback for helping Didi")
	game.command("use rope on railing")
	_check(game.command("look railing").contains("securely knotted"), "Railing describes the secured rope")
	_commands(["go balcony", "use mallet on window"])
	_check(game.objective().begins_with("Take the espresso voucher"), "Objective does not skip collecting the exposed voucher")
	_check(game.command("look window").contains("Take it"), "Open window explicitly offers the voucher")
	_check(game.get_hotspot("window").label == "Open service window", "Window label reflects its open state")
	game.command("take voucher")
	_check(game.command("look window").contains("sill is empty"), "Window LOOK reflects voucher pickup")
	_check(game.command("look").contains("collected"), "Fire escape prose reflects voucher pickup")
	_check(game.objective().begins_with("Redeem the voucher"), "Carried voucher objective points to redemption")
	_commands(["go backroom", "go bar", "go street", "go shop", "use voucher on espresso machine"])
	_check(game.objective().begins_with("Bring the espresso") and not game.objective().contains("voucher"), "Carried coffee objective does not repeat redemption")
	_check(game.command("talk clerk").contains("espresso's ready"), "Clerk acknowledges redeemed coffee")
	_commands(["go street", "go hotel"])
	_check(game.command("talk receptionist").contains("hand it over"), "Receptionist notices the carried espresso")
	game.command("give coffee to receptionist")
	_check(game.objective().contains("introduce yourself to Eve"), "Post-coffee guidance motivates the rooftop visit before gardening")
	_check(game.hint().contains("TALK to Eve"), "Post-coffee hint agrees with objective")
	_check(game.command("look receptionist").contains("espresso you brought"), "Receptionist LOOK reflects the completed favor")
	_check(game.command("look elevator").contains("unlocked"), "Elevator LOOK no longer presents a completed invitation gate")
	_check(game.command("look").contains("sips your espresso"), "Hotel prose reflects the completed favor")
	_commands(["go penthouse", "go rooftop", "talk eve"])
	_check(game.objective().begins_with("Grow a fresh apple"), "Eve's request supplies the gardening objective")
	notes_before = game.journal.size()
	game.command("talk eve")
	_check(game.journal.size() == notes_before, "Eve's food request is remembered once")
	_commands(["go penthouse", "go hotel", "go garden", "take stool", "plant seeds"])
	_check(game.command("look planter").contains("Add a pitcher of water"), "Planted seeds request only their remaining water step")
	_check(game.command("look").contains("waiting for water"), "Garden prose reflects planted seeds")
	_commands(["go hotel", "go penthouse", "use stool on cabinet"])
	_check(game.command("look cabinet").contains("easy to reach"), "Cabinet acknowledges the placed stool")
	game.command("take pitcher")
	_check(game.command("look cabinet").contains("empty"), "Cabinet acknowledges collected pitcher")
	_check(game.command("look").contains("cabinet is empty"), "Penthouse prose acknowledges pitcher pickup")
	_commands(["fill pitcher", "go hotel", "go garden", "water planter"])
	_check(game.objective().begins_with("Take the ripe apple"), "Objective does not skip the final apple pickup")
	_check(game.command("look planter").contains("ready to take"), "Watered planter describes the ripe apple")
	_check(game.get_hotspot("tree").x == 0.49 and game.get_hotspot("tree").y == 0.40, "Tree interaction aligns with the planter art")
	game.command("take apple")
	_check(game.command("look tree").contains("picked clean"), "Tree LOOK acknowledges harvesting")
	_check(game.command("look planter").contains("machine's work is done"), "Planter LOOK acknowledges completed growth puzzle")
	_check(game.command("look").contains("picked its one perfect apple"), "Garden prose acknowledges harvested fruit")
	_check(game.objective().begins_with("Bring Eve"), "Collected fruit objective points to delivery")
	print("Narrative tests: %d assertions, %d failures." % [assertions, failures.size()])
	quit(0 if failures.is_empty() else 1)
