extends SceneTree

const GameState = preload("res://scripts/game_state.gd")
var failures: Array[String] = []
var assertions := 0


func _init() -> void:
	_run.call_deferred()


func _check(condition: bool, message: String) -> void:
	assertions += 1
	if not condition:
		failures.append(message)
		printerr("FAIL: " + message)


func _go(game: RefCounted, destination: String) -> void:
	var response: String = game.travel(destination)
	_check(game.room == destination, "Travel to %s: %s" % [destination, response])


func _act(game: RefCounted, target: String, verb: String = "use", item: String = "") -> String:
	var response: String = game.interact(target, verb, item)
	_check(not response.is_empty(), "Interaction returns useful prose: " + target)
	return response


func _run() -> void:
	var game = GameState.new()
	_check(game.rooms.size() == 13, "All 13 rooms exist")
	_check(game.room == "street" and game.cash == 80 and game.score == 0, "New game starts cleanly")
	_check(not game.hint().is_empty() and not game.objective().is_empty(), "Help exists immediately")
	for id in game.rooms:
		var data: Dictionary = game.get_room(id)
		_check(data.has("name") and data.has("description") and data.has("background") and data.has("hotspots") and data.has("exits"), "Room schema: " + id)
		for spot in data.hotspots:
			_check(spot.x >= 0 and spot.x <= 1 and spot.y >= 0 and spot.y <= 1, "Hotspot coordinates: " + str(spot.id))
	_check(game.travel("penthouse").contains("direct route"), "Travel cannot teleport into locked rooms")
	_check(game.travel("unknown").contains("questionable"), "Invalid room is rejected")
	_check(game.command("take moon").contains("cannot see"), "Unknown target is rejected")
	_check(game.command("explode universe").contains("parse"), "Unknown verb is rejected")
	_check(game.interact("taxi", "use", "knife").contains("not carrying"), "Unowned items cannot be used")
	_check(game.command("north").contains("named exit"), "Compass commands explain navigation")
	_check(game.command("inventory").contains("$80"), "Inventory includes funds")
	_check(game.command("read newspaper").contains("Free papers"), "Uncollected newspaper can be examined at source")
	game.command("take newspaper")
	game.command("read newspaper")
	_check(game.flags.get("newspaper_read", false), "Reading paper teaches planter controls")
	game.command("buy flowers")
	_check(game.inventory.has("flowers") and game.cash == 70, "Flower purchase works")
	game.command("buy flowers")
	_check(game.cash == 70, "Repeated purchase does not charge twice")
	_check(game.travel("disco").contains("requires a pass") and game.room == "street", "Disco pass gate")
	_go(game, "bar")
	_check(game.travel("backroom").contains("password"), "Backstage gate blocks before password")
	game.command("buy whiskey")
	game.command("give whiskey to regular")
	_check(game.inventory.has("remote") and not game.inventory.has("whiskey"), "Regular trades remote for whiskey")
	var wallet: int = game.cash
	game.command("buy whiskey")
	_check(game.cash == wallet, "Consumed quest purchases cannot charge again")
	_go(game, "bathroom")
	game.command("read graffiti")
	game.command("take ring")
	_check(game.flags.get("password_known", false), "Graffiti reveals password")
	_check(game.get_hotspot("ring").is_empty(), "Collected props disappear")
	_go(game, "bar")
	game.command("say wrongpassword")
	_check(not game.flags.get("password_spoken", false), "Wrong password does not unlock")
	game.command("BELLYBUTTON")
	_check(not game.is_unlocked("backroom"), "Password alone does not distract bouncer")
	game.command("use remote on tv")
	_check(game.is_unlocked("backroom"), "Password plus TV unlock backstage")
	_go(game, "backroom")
	game.command("take candy")
	_check(not game.is_unlocked("balcony"), "Balcony requires anchored safety rope")
	_go(game, "bar")
	_go(game, "street")
	_go(game, "casino")
	game.command("take pass")
	var starting_cash: int = game.cash
	var payouts: Array[int] = [-5, 10, -5, 20]
	for change in payouts:
		game.command("play slots")
		starting_cash += change
		_check(game.cash == starting_cash, "Casino fixed transparent payout cycle")
	game.cash = 0
	game.command("talk cashier")
	_check(game.cash == 20, "Cashier rescues an empty wallet")
	game.command("talk cashier")
	_check(game.cash == 20, "Recovery grant cannot stack above threshold")
	for spin in range(8): game.command("play slots")
	_check(game.cash == 60, "Recovery and deterministic play rebuild quest funds")
	_go(game, "street")
	_go(game, "disco")
	game.command("give ring to didi")
	_check(game.inventory.has("ring"), "Gifts require introduction, preserve inventory")
	game.command("call 555-0987")
	_check(not game.flags.get("phone_called", false), "Phone requires contextual introduction")
	game.command("talk to didi")
	game.command("dance")
	game.command("give ring to didi")
	game.command("give candy to didi")
	game.command("give flowers to didi")
	_check(game.flags.get("phone_known", false), "Props and dance reveal phone number")
	game.command("call 555-0000")
	_check(not game.flags.get("phone_called", false), "Wrong phone number rejected")
	game.command("call 555-0987")
	_check(game.flags.get("phone_called", false), "Stage manager authorizes rope")
	_go(game, "street")
	_go(game, "shop")
	game.command("buy wine")
	_go(game, "street")
	_go(game, "alley")
	game.command("give wine to busker")
	game.command("take rubber mallet")
	game.command("take apple core")
	game.command("use apple core")
	_check(game.inventory.has("knife") and game.inventory.has("hammer") and game.inventory.has("seeds"), "Alley trade and extraction succeed")
	_go(game, "street")
	_go(game, "disco")
	game.command("use knife on spare rope")
	_check(game.inventory.has("rope"), "Authorized rope is cut free")
	game.command("use knife on spare rope")
	_check(game.inventory.count("rope") == 1, "Rope cannot duplicate")
	_go(game, "street")
	_go(game, "bar")
	_go(game, "backroom")
	game.command("use rope on railing")
	_check(game.is_unlocked("balcony") and not game.inventory.has("rope"), "Anchored rope unlocks fire escape")
	_go(game, "balcony")
	_check(game.get_hotspot("voucher").is_empty(), "Voucher hidden until window opens")
	game.command("take voucher")
	_check(not game.inventory.has("voucher"), "Hidden voucher cannot be taken")
	game.command("use mallet on window")
	game.command("take voucher")
	_check(game.inventory.has("voucher"), "Mallet opens window to voucher")
	_go(game, "backroom")
	_go(game, "bar")
	_go(game, "street")
	_go(game, "shop")
	game.command("use voucher on espresso machine")
	_check(game.inventory.has("coffee") and not game.inventory.has("voucher"), "Voucher becomes espresso")
	_go(game, "street")
	_go(game, "hotel")
	_check(game.travel("penthouse").contains("receptionist"), "Receptionist invitation gate")
	game.command("give coffee to receptionist")
	_check(game.flags.get("penthouse_access", false), "Coffee earns freely offered invitation")
	_go(game, "garden")
	game.command("take stool")
	game.command("plant seeds")
	_check(game.flags.get("seeds_planted", false), "Planter accepts seeds")
	_go(game, "hotel")
	_go(game, "penthouse")
	game.command("take pitcher")
	_check(not game.inventory.has("pitcher"), "High cabinet blocks unassisted reach")
	game.command("use stool on cabinet")
	game.command("take pitcher")
	game.command("fill pitcher")
	_check(game.flags.get("pitcher_filled", false), "Pitcher fills at sink")
	_check(game.get_inventory().filter(func(entry): return entry.id == "pitcher")[0].name == "Pitcher of water", "Inventory reflects water state")
	_go(game, "hotel")
	_go(game, "garden")
	game.command("water planter")
	_check(game.flags.get("apple_grown", false), "Water grows apple tree")
	game.command("take apple")
	_check(game.inventory.has("apple"), "Apple can be harvested")
	var score_before_repeat: int = game.score
	game.command("take apple")
	_check(game.inventory.count("apple") == 1 and game.score == score_before_repeat, "Apple and points do not duplicate")
	_go(game, "hotel")
	_go(game, "penthouse")
	_go(game, "rooftop")
	game.command("give apple to eve")
	_check(game.inventory.has("apple"), "Eve receives an introduction before gifts")
	game.command("talk eve")
	game.command("give apple to eve")
	_check(not game.completed, "Final conversation is player initiated")
	var story: String = game.command("talk eve")
	_check(not game.completed and story.contains("knees"), "Finale tells a concrete story before completion")
	var reply: String = game.command("talk eve")
	_check(not game.completed and reply.contains("design these gardens"), "Finale lets Larry learn about Eve")
	var ending: String = game.command("talk eve")
	_check(game.completed and ending.contains("THE END"), "Complete adventure reaches affirmative ending")
	_check(game.score == game.max_score, "Complete route earns 100 points, got %d" % game.score)
	game.command("talk eve")
	_check(game.score == 100, "Ending cannot award twice")
	_check(game.journal.size() >= 20, "Journal preserves adventure clues")
	var snapshot := JSON.stringify({"room": game.room, "inventory": game.inventory, "flags": game.flags, "cash": game.cash, "score": game.score, "turns": game.turns, "completed": game.completed, "journal": game.journal})
	var save_path := "user://test_game_state.json"
	_check(game.save_game(save_path).contains("saved"), "Save succeeds")
	game.new_game()
	_check(game.room == "street" and game.inventory.is_empty() and game.score == 0 and not game.completed and game.flags.is_empty(), "New game fully resets state")
	_check(game.load_game(save_path).contains("restored"), "Save reload succeeds")
	var restored := JSON.stringify({"room": game.room, "inventory": game.inventory, "flags": game.flags, "cash": game.cash, "score": game.score, "turns": game.turns, "completed": game.completed, "journal": game.journal})
	_check(restored == snapshot, "Save restores all gameplay state exactly")
	var broken := FileAccess.open("user://test_broken.json", FileAccess.WRITE)
	broken.store_string("not json")
	broken.close()
	_check(game.load_game("user://test_broken.json").contains("unchanged") and game.completed, "Invalid save preserves current game")
	_check(game.load_game("user://does_not_exist_larry.json").contains("No saved"), "Missing save handled")
	var corrupt := FileAccess.open("user://test_broken.json", FileAccess.WRITE)
	corrupt.store_string(JSON.stringify({"version": 1, "room": "street", "inventory": ["nonexistent"], "flags": {}, "journal": [], "cash": 5, "score": 0, "turns": 0, "completed": false}))
	corrupt.close()
	_check(game.load_game("user://test_broken.json").contains("unknown item") and game.completed, "Invalid inventory cannot partially replace state")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(save_path))
	DirAccess.remove_absolute(ProjectSettings.globalize_path("user://test_broken.json"))
	# Exercise every visible hotspot's look contract, without mutating the finished game.
	var inspector = GameState.new()
	for id in inspector.rooms:
		inspector.room = id
		for spot in inspector.get_room().hotspots:
			_check(not inspector.interact(spot.id, "look").contains("cannot see"), "Visible hotspot has look response: %s/%s" % [id, spot.id])
	print("Adventure tests: %d assertions, %d failures." % [assertions, failures.size()])
	quit(0 if failures.is_empty() else 1)
