import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRequest,evaluate} from '../tools/jev-qa/client.mjs';
const observation={revision:1,room:'bar',objective:'Make a useful trade',dialogue:'The regular wants whiskey.',score:0,actions:[{id:'a001',label:'Use Lefty: buy whiskey'}],diagnostics:{fps:60}};
test('closed candidates and abstention; no diagnostics given to model',()=>{const q=buildRequest({persona:'goal',observation});assert.equal(q.questions.next_action.criteria.a001,'Use Lefty: buy whiskey');assert.ok(q.questions.next_action.criteria.abstain);assert.equal(q.state.visible.diagnostics,undefined);});
test('unguided condition removes objective from current state AND history',()=>{const q=buildRequest({persona:'unguided',observation,history:[{objective:'secret prompt',action:'Talk',dialogue:'Known clue'}]});assert.equal(q.state.visible.objective,undefined);assert.equal(q.state.recent_actions[0].objective,undefined);});
test('invalid profiles and incomplete candidate coverage fail closed',()=>{assert.throws(()=>buildRequest({persona:'unknown',observation}));assert.throws(()=>buildRequest({persona:'goal',observation:{actions:Array(255).fill({id:'a',label:'x'})}}));});
test('provider HTTP failure stops without retry or logging credentials',async()=>{let calls=0;await assert.rejects(evaluate(buildRequest({persona:'goal',observation}),{apiKey:'test-only-key',fetchImpl:async()=>{calls++;return{ok:false,status:429};}}),/HTTP 429/);assert.equal(calls,1);});
test('unsupported model action never reaches executor',async()=>{await assert.rejects(evaluate(buildRequest({persona:'goal',observation}),{apiKey:'test-only-key',fetchImpl:async()=>({ok:true,json:async()=>({model:'jev-test',usage:{},answers:{next_action:{choice:'destroy'}}})})}),/unsupported choice/);});
test('duplicate candidate IDs are rejected instead of silently collapsed',()=>{assert.throws(()=>buildRequest({persona:'goal',observation:{actions:[{id:'same',label:'one'},{id:'same',label:'two'}]}}),/duplicate/);});
test('255 bridge options including decline stay within API limit',()=>{const actions=Array.from({length:254},(_,i)=>({id:`a${i}`,label:`Action ${i}`}));actions.push({id:'decline',label:'Stop'});assert.equal(Object.keys(buildRequest({persona:'goal',observation:{actions}}).questions.next_action.criteria).length,255);});
test('negative provider usage is rejected',async()=>{await assert.rejects(evaluate(buildRequest({persona:'goal',observation}),{apiKey:'test-only-key',fetchImpl:async()=>({ok:true,json:async()=>({model:'jev-test',usage:{input_tokens:-1,output_tokens:0},answers:{next_action:{choice:'a001'}}})})}),/Invalid TypeSafe usage/);});
test('missing judge fields are rejected',async()=>{await assert.rejects(evaluate(buildRequest({persona:'goal',observation}),{apiKey:'test-only-key',fetchImpl:async()=>({ok:true,json:async()=>({model:'jev-test',usage:{input_tokens:1,output_tokens:1},answers:{next_action:{type:'choice',choice:'a001',confidence:1,probabilities:{a001:1,abstain:0}}}})})}),/Missing or invalid/);});
import {Budget,validateConfig,runPool,remember,ProgressTracker,orderCandidates,acceptsMessage,disposeWorkers} from '../tools/jev-qa/runner.mjs';
import {CRITIC_FIXTURES,criticMetrics} from '../tools/jev-qa/critic-fixtures.mjs';
import {createLab} from '../tools/jev-qa/server.mjs';
import {mkdtemp,rm,readFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {gunzipSync} from 'node:zlib';
function answerFor(request){return {model:'jev-test-version',usage:{input_tokens:20,output_tokens:5},answers:Object.fromEntries(Object.entries(request.questions).map(([id,q])=>{const keys=q.type==='choice'?Object.keys(q.criteria):q.type==='score'?q.criteria.map((_,i)=>String(i)):[];return [id,q.type==='noul'?{type:q.type,noul:.1}:q.type==='choice'?{type:q.type,choice:keys[0],confidence:1,probabilities:Object.fromEntries(keys.map((k,i)=>[k,i===0?1:0]))}:{type:q.type,score:0,confidence:1,probabilities:Object.fromEntries(keys.map((k,i)=>[k,i===0?1:0]))}];}))};}
test('valid typed answers retain model and all distributions',async()=>{const request=buildRequest({persona:'goal',observation});const response=answerFor(request);const got=await evaluate(request,{apiKey:'test-key',fetchImpl:async()=>({ok:true,json:async()=>response})});assert.deepEqual(got.result,response);});
test('unknown strategy choice is rejected independently of player action',async()=>{const request=buildRequest({persona:'goal',observation});const response=answerFor(request);response.answers.strategy.choice='invented';await assert.rejects(evaluate(request,{apiKey:'x',fetchImpl:async()=>({ok:true,json:async()=>response})}),/unsupported choice/);});
test('incomplete, negative and unnormalized distributions fail closed',async()=>{for(const probabilities of [{a001:1},{a001:1,abstain:-.1},{a001:.8,abstain:.8}]){const request=buildRequest({persona:'goal',observation});const response=answerFor(request);response.answers.next_action.probabilities=probabilities;await assert.rejects(evaluate(request,{apiKey:'x',fetchImpl:async()=>({ok:true,json:async()=>response})}),/distribution/);}});
function waitingFetch(_url,{signal}){return new Promise((resolve,reject)=>{const keepAlive=setTimeout(()=>resolve({ok:false,status:504}),1000);const abort=()=>{clearTimeout(keepAlive);reject(signal.reason);};if(signal.aborted)abort();else signal.addEventListener('abort',abort,{once:true});});}
test('timeout is bounded and never retried',async()=>{let calls=0;await assert.rejects(evaluate(buildRequest({persona:'goal',observation}),{apiKey:'x',timeoutMs:10,fetchImpl:(...args)=>{calls++;return waitingFetch(...args);}}),e=>e.name==='TimeoutError');assert.equal(calls,1);});
test('explicit cancellation aborts an active request without retry',async()=>{const controller=new AbortController();const promise=evaluate(buildRequest({persona:'goal',observation}),{apiKey:'x',signal:controller.signal,fetchImpl:waitingFetch});controller.abort();await assert.rejects(promise,e=>e.name==='AbortError');});
test('config accepts 2/4/8 workers, 100 runs, 160 default actions; rejects unbounded values',()=>{for(const workers of [2,4,8])assert.equal(validateConfig({workers,runCount:100}).maxSteps,160);for(const data of [{workers:9},{workers:3},{runCount:101},{maxSteps:201},{maxRequests:20001},{maxCostUSD:0},{maxInputTokens:Infinity}])assert.throws(()=>validateConfig(data));});
test('100 mock sessions complete once each with at most eight workers',async()=>{let active=0,maxActive=0;const indices=[];const result=await runPool(100,8,async i=>{active++;maxActive=Math.max(active,maxActive);await new Promise(r=>setTimeout(r,1));indices.push(i);active--;return i;});assert.equal(maxActive,8);assert.equal(new Set(indices).size,100);assert.deepEqual(result,Array.from({length:100},(_,i)=>i));});
test('scheduler cancellation launches no next wave',async()=>{let stop=false,started=0;await runPool(100,8,async()=>{started++;await new Promise(r=>setTimeout(r,1));stop=true;},()=>stop);assert.equal(started,8);});
test('hard attempt/concurrency limits reserve before dispatch and include failures',()=>{const budget=new Budget({workers:2,maxRequests:3});const a=budget.reserve(),b=budget.reserve();assert.throws(()=>budget.reserve(),/concurrency/);a({input_tokens:10,output_tokens:1});b();const c=budget.reserve();assert.throws(()=>budget.reserve(),/request_budget/);c({input_tokens:10,output_tokens:1});assert.deepEqual([budget.requests,budget.active,budget.errors],[3,0,1]);assert.throws(()=>c(),/twice/);});
test('input and cost thresholds and cancellation stop later dispatch',()=>{const input=new Budget({maxInputTokens:1000});input.reserve()({input_tokens:1001,output_tokens:0});assert.throws(()=>input.reserve(),/input_token/);const cost=new Budget({maxCostUSD:.001});cost.reserve()({input_tokens:30000,output_tokens:0});assert.throws(()=>cost.reserve(),/cost/);const cancel=new Budget({});cancel.cancelled=true;assert.throws(()=>cancel.reserve(),/cancelled/);});
const visible=(room='bar',extra={})=>({room:{id:room,title:room},score:0,inventory:[],notebook:[],hotspots:[{name:'counter'}],overlay:[],...extra});
test('cycle detector catches alternating room/action loops',()=>{const tracker=new ProgressTracker();tracker.update(visible('bar'));let status;for(let i=0;i<10;i++)status=tracker.update(visible(i%2?'bar':'shop'),'Travel '+(i%2?'bar':'shop'));assert.equal(status.stop,true);assert.equal(status.cyclePeriod,2);});
test('new clue, inventory, score or visible object resets cycle escalation',()=>{for(const change of [{notebook:['new clue']},{inventory:['remote']},{score:4},{hotspots:[{name:'new tree'}]}]){const tracker=new ProgressTracker();for(let i=0;i<4;i++)tracker.update(visible(),'Look counter');const status=tracker.update(visible('bar',change),'Look counter');assert.equal(status.progress,true);assert.equal(status.stop,false);assert.equal(status.noProgress,0);}});
test('changing wallet and revisiting rooms is not new evidence',()=>{const tracker=new ProgressTracker();for(let i=0;i<30;i++)tracker.update(visible('bar',{money:i}),'Unproductive attempt '+i);assert.equal(tracker.noProgress,29);assert.equal(tracker.update(visible()).reason,'no_observed_progress');});
test('observed-room memory keeps labels and current labels separately',()=>{const memory={};remember(memory,visible('bar',{dialogue:{text:'Bring whiskey.'}}));remember(memory,visible('bar',{hotspots:[{name:'empty glass'}],dialogue:{text:'Thanks.'}}));assert.deepEqual(memory.bar.hotspots,['counter','empty glass']);assert.deepEqual(memory.bar.currentHotspots,['empty glass']);assert.deepEqual(memory.bar.dialogue,['Bring whiskey.','Thanks.']);});
test('candidate shuffling is reproducible, varied, complete and non-mutating',()=>{const actions=Array.from({length:20},(_,i)=>({id:String(i),label:String(i)}));const copy=structuredClone(actions);assert.deepEqual(orderCandidates(actions,1),orderCandidates(actions,1));assert.notDeepEqual(orderCandidates(actions,1),orderCandidates(actions,2));assert.deepEqual(orderCandidates(actions,1).map(a=>a.id).sort(),actions.map(a=>a.id).sort());assert.deepEqual(actions,copy);});
test('parent ignores wrong origin, old worker source and stale request IDs',()=>{const source={},event={origin:'http://local',source,data:{type:'larry-qa-observation',requestId:'fresh'}};assert.equal(acceptsMessage(event,'http://local',source,'fresh'),true);for(const e of [{...event,origin:'https://evil'},{...event,source:{}},{...event,data:{...event.data,requestId:'old'}}])assert.equal(acceptsMessage(e,'http://local',source,'fresh'),false);});
test('critic fixtures preserve bouncer regression, balanced negatives and defined metrics',()=>{assert.equal(CRITIC_FIXTURES.filter(f=>f.kind==='dialogue').length,40);assert.equal(CRITIC_FIXTURES.filter(f=>f.kind==='clue').length,20);assert.equal(CRITIC_FIXTURES[0].id,'tv-before-password-stale');const records=CRITIC_FIXTURES.map(f=>({...f,result:{answers:{contradiction:{noul:f.expected?.9:.1},clarity:{score:f.expected?3:0}}}}));const m=criticMetrics(records);assert.equal(m.dialogue.precision,1);assert.equal(m.dialogue.recall,1);assert.equal(m.clue.precision,1);records[0].result.answers.contradiction.noul=.1;assert.ok(criticMetrics(records).dialogue.misses.includes('tv-before-password-stale'));});
test('live server contract protects key, run registration, duplicate steps and compressed evidence',async()=>{
 const output=await mkdtemp(path.join(tmpdir(),'jev-lab-test-'));const origin='http://127.0.0.1:18767';let calls=0;
 const lab=await createLab({apiKey:'fixture-secret-never-exported',output,origin,evaluateFn:async request=>{calls++;return {result:answerFor(request),apiMs:2};}});
 await new Promise(r=>lab.server.listen(18767,'127.0.0.1',r));const post=async(route,data,token=lab.token)=>fetch(origin+route,{method:'POST',headers:{Origin:origin,'X-QA-Token':token,'Content-Type':'application/json'},body:JSON.stringify(data)});
 try{
  assert.equal((await post('/batch',{},'wrong')).status,403);const b=await (await post('/batch',{runCount:2,maxRequests:1})).json();assert.equal(b.runs.length,2);assert.notEqual(b.runs[0].id,b.runs[1].id);
  const request={runId:b.runs[0].id,persona:b.runs[0].persona,step:0,observation};assert.equal((await post('/decide',{...request,runId:'unknown'})).status,400);assert.equal((await post('/decide',request)).status,200);assert.equal((await post('/decide',request)).status,409);
  assert.equal((await post('/decide',{...request,runId:b.runs[1].id,persona:b.runs[1].persona})).status,429);assert.equal(calls,1);
  await post('/result',{runId:request.runId,status:'finished',reason:'test_complete',completed:false,steps:1});await post('/stop',{});await lab.finished();
  const summary=await readFile(path.join(output,b.batchId,'summary.json'),'utf8');assert.equal(summary.includes('fixture-secret'),false);assert.equal(JSON.parse(summary).budget.requests,1);
  const files=await readdir(path.join(output,b.batchId));assert.ok(files.some(f=>f.endsWith('.jsonl.gz')));const records=gunzipSync(await readFile(path.join(output,b.batchId,request.runId+'.jsonl.gz'))).toString();assert.equal(records.includes('fixture-secret'),false);assert.ok(records.includes('jev-test-version'));assert.ok(records.includes('criteria'));
  assert.equal((await fetch(origin+'/.env')).status,404);
 }finally{lab.server.closeAllConnections();await new Promise(r=>lab.server.close(r));await lab.finished();await rm(output,{recursive:true,force:true});}
});
test('model state explicitly whitelists visible fields, excluding future hidden/debug fields',()=>{const request=buildRequest({persona:'goal',observation:{...observation,flags:{password_known:true},diagnostics:{fps:60},internalSolution:'secret'}});assert.equal(request.state.visible.flags,undefined);assert.equal(request.state.visible.internalSolution,undefined);});
test('server stop cancels active inference, rejects duplicate inflight steps, and records unknown failed usage',async()=>{
 const output=await mkdtemp(path.join(tmpdir(),'jev-cancel-test-'));const origin='http://127.0.0.1:18768';let started;const invoked=new Promise(r=>started=r);let calls=0;
 const lab=await createLab({apiKey:'cancellation-secret',output,origin,evaluateFn:async(_request,{signal})=>{calls++;started();return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('Cancelled cancellation-secret')),{once:true}));}});
 await new Promise(r=>lab.server.listen(18768,'127.0.0.1',r));const post=(route,data)=>fetch(origin+route,{method:'POST',headers:{Origin:origin,'X-QA-Token':lab.token,'Content-Type':'application/json'},body:JSON.stringify(data)});
 try{const batch=await(await post('/batch',{runCount:2})).json();const run=batch.runs[0];const payload={runId:run.id,persona:run.persona,step:0,observation};const pending=post('/decide',payload);await invoked;assert.equal((await post('/decide',payload)).status,409);await post('/stop',{});assert.equal((await pending).status,502);await lab.finished();const snapshot=lab.snapshot();assert.equal(snapshot.budget.active,0);assert.equal(snapshot.budget.errors,1);assert.equal(snapshot.runs[batch.runs[1].id].reason,'cancelled_before_start');assert.equal(calls,1);const log=gunzipSync(await readFile(path.join(output,batch.batchId,run.id+'.jsonl.gz'))).toString();assert.ok(log.includes('usageUnknown'));assert.equal(log.includes('cancellation-secret'),false);}
 finally{lab.server.closeAllConnections();await new Promise(r=>lab.server.close(r));await lab.finished();await rm(output,{recursive:true,force:true});}
});
test('a failed worker stops future waves and waits for already running workers',async()=>{let started=0,settled=0;await assert.rejects(runPool(100,8,async i=>{started++;await new Promise(r=>setTimeout(r,1));settled++;if(i===0)throw Error('worker failed');}),/worker failed/);assert.equal(started,8);assert.equal(settled,8);});
test('independent critics receive visible control labels in shared state, not only another question criteria',()=>{const request=buildRequest({persona:'goal',observation});assert.deepEqual(request.state.visible.available_actions,['Use Lefty: buy whiskey']);assert.equal(request.state.visible.actions,undefined);});

test('switching from eight completed workers to four disposes every old iframe before replacement',()=>{
 const retired=[],players=new Map();for(let i=0;i<8;i++)players.set(i,{frame:{src:'live-game-'+i,remove(){retired.push('frame'+i);}},card:{remove(){retired.push('card'+i);}},ready:null,pending:null});
 const old=[...players.values()];assert.equal(disposeWorkers(players),8);assert.equal(players.size,0);assert.equal(retired.length,16);assert.ok(old.every(p=>p.frame.src==='about:blank'));
 for(let i=0;i<4;i++)players.set(i,{frame:{},card:{}});assert.equal(players.size,4);assert.ok(!players.has(4)&&!players.has(7));
});
test('worker disposal unregisters sources first and cancels remaining callbacks',()=>{let rejected=0;const players=new Map();const pending={timer:setTimeout(()=>{},1000),reject(){rejected++;assert.equal(players.size,0);}};players.set(0,{frame:{src:'game',remove(){}},card:{remove(){}},pending,ready:null});disposeWorkers(players);assert.equal(rejected,1);});

test('dashboard blocks a second Start submission while batch registration is pending',async()=>{
 const source=(await readFile(new URL('../tools/jev-qa/dashboard.js',import.meta.url),'utf8')).replace(/^import[^\n]+\n/,'');
 const elements=new Map();let submit,registrations=0,resolveBatch;
 const document={querySelector(selector){if(!elements.has(selector))elements.set(selector,{disabled:false,textContent:'',replaceChildren(){},addEventListener(type,handler){if(selector==='#settings'&&type==='submit')submit=handler;}});return elements.get(selector);}};
 const fetch=async route=>{if(route==='/config')return {json:async()=>({defaults:{},token:'fixture',buildId:'fixture-build'})};assert.equal(route,'/batch');registrations++;return new Promise(resolve=>{resolveBatch=()=>resolve({ok:true,json:async()=>({batchId:'fixture-batch',config:{workers:4,runCount:100},runs:[]})});});};
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 await new AsyncFunction('validateConfig','runPool','remember','ProgressTracker','acceptsMessage','disposeWorkers','fetch','window','document','FormData',source)(validateConfig,async()=>[],remember,ProgressTracker,acceptsMessage,disposeWorkers,fetch,{addEventListener(){}},document,class{constructor(){return [['workers','4'],['runCount','100']];}});
 const event={preventDefault(){},currentTarget:{}};const first=submit(event);await submit(event);assert.equal(registrations,1);assert.equal(elements.get('#start').disabled,true);resolveBatch();await first;assert.equal(elements.get('#start').disabled,false);
});
