import {readdir,readFile,writeFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import path from 'node:path';
const root=process.argv[2]??'docs/experiments/jev';
const quantile=(values,p)=>{const sorted=values.filter(Number.isFinite).sort((a,b)=>a-b);return sorted[Math.floor((sorted.length-1)*p)]??null;};
async function directories(dir){const result=[];for(const entry of await readdir(dir,{withFileTypes:true})){if(entry.isDirectory())result.push(...await directories(path.join(dir,entry.name)));else if(entry.name==='summary.json')result.push(dir);}return result;}
const batches=[];
for(const dir of await directories(root)){
 const summary=JSON.parse(await readFile(path.join(dir,'summary.json'),'utf8'));let decisions=[],events=[];
 if(summary.batchId){for(const entry of await readdir(dir)){if(entry.endsWith('.jsonl.gz')){const records=gunzipSync(await readFile(path.join(dir,entry))).toString().trim().split('\n').filter(Boolean).map(JSON.parse);decisions.push(...records.filter(x=>x.type==='decision'));events.push(...records.filter(x=>x.type==='outcome'));}}}
 else{for(const [filename,destination] of [['decisions.jsonl',decisions],['events.jsonl',events]]){try{destination.push(...(await readFile(path.join(dir,filename),'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse));}catch{}}}
 const players={};for(const [id,run]of Object.entries(summary.runs)){
  const steps=events.filter(e=>e.runId===id&&e.status==='running'),qs=decisions.filter(d=>d.runId===id),actions=steps.map(s=>s.lastAction);const frequencies={};for(const label of actions)frequencies[label]=(frequencies[label]||0)+1;
  players[id]={persona:run.persona??id,score:run.score,completed:!!run.completed,steps:run.steps,reason:run.reason,errors:run.errors,rooms:[...new Set(steps.map(s=>s.room?.id))],uniqueActions:new Set(actions).size,mostRepeated:Object.entries(frequencies).sort((a,b)=>b[1]-a[1]).slice(0,3),actionMs:{p50:quantile(steps.map(s=>s.actionMs),.5),p95:quantile(steps.map(s=>s.actionMs),.95)},sampledFps:{min:steps.length?Math.min(...steps.map(s=>s.observation?.diagnostics?.fps).filter(Number.isFinite)):null,p50:quantile(steps.map(s=>s.observation?.diagnostics?.fps),.5)},coldLoadMs:run.coldLoadMs,browser:steps.at(-1)?.observation?.diagnostics?.browser,callbackMs:{p50:quantile(steps.map(s=>s.observation?.diagnostics?.action_callback_ms),.5),p95:quantile(steps.map(s=>s.observation?.diagnostics?.action_callback_ms),.95)},settledMs:{p50:quantile(steps.map(s=>s.observation?.diagnostics?.action_settled_ms),.5),p95:quantile(steps.map(s=>s.observation?.diagnostics?.action_settled_ms),.95)},decisionRoundTripMs:{p50:quantile(steps.map(s=>s.decisionRoundTripMs),.5),p95:quantile(steps.map(s=>s.decisionRoundTripMs),.95)},engineStaticMemoryBytes:{first:steps[0]?.observation?.diagnostics?.engine_static_memory_bytes,last:steps.at(-1)?.observation?.diagnostics?.engine_static_memory_bytes},choiceConfidence:{p50:quantile(qs.map(d=>d.result.answers.next_action.confidence),.5)},averageClarity:qs.length?qs.reduce((n,d)=>n+d.result.answers.clarity.score,0)/qs.length:null,visibility:[...new Set(steps.map(s=>s.visibility??'unrecorded'))]};
 }
 const counts={};for(const run of Object.values(players))counts[run.reason??'in_progress']=(counts[run.reason??'in_progress']??0)+1;
 const executed=Object.values(players).filter(r=>r.reason!=='cancelled_before_start');const completed=executed.filter(r=>r.completed).length;const cycles=executed.filter(r=>['repeated_action_cycle','no_observed_progress'].includes(r.reason)).length;
 const browserRuns=Object.values(players).map(p=>p.browser).filter(Boolean);const frameSamples=browserRuns.reduce((n,b)=>n+(b.visibleFrameSamples??0),0);const framesWithin20ms=browserRuns.reduce((n,b)=>n+(b.framesWithin20ms??0),0);
 batches.push({browserFrames:{visibleSamples:frameSamples,framesWithin20ms,fractionWithin20ms:frameSamples?framesWithin20ms/frameSamples:null,notes:'Visible requestAnimationFrame intervals after 2s warmup, not GPU render duration. Per-worker quantiles use 1ms upper-bound histogram bins.'},directory:dir,session:summary.session,batchId:summary.batchId,buildId:summary.buildId,runnerId:summary.runnerId??null,config:summary.config,memoryEnabled:decisions.some(d=>d.request.state.observed_memory),requests:summary.budget.requests,inputTokens:summary.budget.inputTokens,apiErrors:summary.budget.errors,models:[...new Set(decisions.map(d=>d.result.model))],apiLatencyMs:summary.apiLatencyMs,estimatedInputCostUSD:summary.estimatedInputCostUSD,serverMemory:summary.serverMemory,outcomes:counts,executed:executed.length,completed,completionRate:executed.length?completed/executed.length:null,loopStops:cycles,loopStopRate:executed.length?cycles/executed.length:null,players});
}
const result={generatedAt:new Date().toISOString(),batches,limits:'Observed browser UI callback experiments with text-driven agents. No pixel recognition or human enjoyment measurement. Policies and seeded order vary, but repeated model decisions are not independent human subjects. Sampled FPS and server RSS do not establish frame-time or browser-memory targets. Cost excludes unknown usage on failures and is not a bill.'};
const output=path.join(root,'aggregate.json');await writeFile(output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({file:output,batches:batches.map(({players,...batch})=>batch)},null,2));
